# Generated by Django 4.1.2 on 2024-05-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
